Fixed: realpath does not exist on type typeof Deno
Fixed error:

```
TS2551 [ERROR]: Property 'realpath' does not exist on type 'typeof Deno'. Did you mean 'realPath'?
  const fullPath = await Deno.realpath(String(directoryArg));
```